
#*DSM12:
#!ACOSTA ROBLEDO ALONSO VLADIMIR 
#!HERNANDEZ  VELAZQUEZ BRIAN CARLOS
#!HERNÁNDEZ CASTILLO KEVIN AXEL
#! ORTIZ ZAVALA BRYAN 

#*DSM13:
#!ARANDA MADERA JOSÉ ALEJANDRO
#!CASTELLON TELLO SUSAN CITLALY
#!HERNANDEZ NUÑEZ YOJANI ISAIAS
#!MARTINEZ CERVANTES IAN NOE 
#!MEZA RODRÍGUEZ DANNA VICTORIA 
#!RAMIREZ IBARRA LORENZO ANGEL 
#!ROSALES GUTIÉRREZ ALEX YAEL 
#!SANDOVAL MEDINA MANUEL ALEJANDRO 

#*DSM14:
#!CERNA MIRAMONTES PAVEL JARED 
#!ESTRADA CASTILLO ASHLEY JIMENA
#!NUNGARAY LAVEAGA ANNUAR ERANDI 

#*IA11
#!CARRILLO JACOME EDWIN GABRIEL
#!CASTRO GALVAN ANGEL
#!MARTINEZ RUBIO LUIS TONATHIU
#!ROBLES PEREZ EMILY GUADALUPE
#!ROBLES SANCHEZ MARIA JAZMIN
#!SANCHEZ RODRIGUEZ DIEGO ALEXANDER
#!TORRES NAVARRETE CHRISTOFER GERARDO
#!VILLALOBOS MACIAS JOSE LUIS




